export const ADD_FILLING_T0_CONSTRUCTOR = 'ADD_FILLING_T0_CONSTRUCTOR';
export const ADD_BUN_T0_CONSTRUCTOR = 'ADD_BUN_T0_CONSTRUCTOR';
export const DEL_FILLING_T0_CONSTRUCTOR = 'DEL_FILLING_T0_CONSTRUCTOR';
export const ADD_IN_T0_CONSTRUCTOR = 'ADD_IN_T0_CONSTRUCTOR';
export const INCREASE_COUTER = 'INCREASE_COUTER';
export const DECREASE_COUTER = 'DECREASE_COUTER';
